@startuml
class arcgis.raster._RasterInfo.RasterInfo {
  _band_count: None
  _extent: None
  _pixel_size_x: None
  _pixel_size_y: None
  _pixel_type: None
  _block_height: None
  _block_width: None
  _spatial_reference: None
  _no_data_values: None
  _dict: None
}
class arcgis.raster._layer.ImageryLayer {
  _datastore_raster: None
  _uri: None
  _gis: None
  _datastore_raster: None
  _uri: None
  _uri: None
  _lazy_token: None
  _spatial_filter: None
  _temporal_filter: None
  _where_clause: None
  _fn: None
  _fnra: None
  _filtered: None
  _mosaic_rule: None
  _extent: None
  _uses_gbl_function: None
  _other_outputs: None
  _raster_info: None
  _tiles_only: None
  _extent_set: None
  _original_info: None
  _rendering_rule_from_item: None
}
class arcgis.raster._layer.ImageryLayerCacheManager {
  _img_lyr: None
  _gis: None
  _url: None
}
class arcgis.raster._layer.ImageryTileManager {
  _service: None
  _url: None
  _con: None
}
class arcgis.raster._layer.Raster {
  _engine_obj: None
  _engine: None
  _engine: None
  _engine_obj: None
  extent: Optional[dict]
  cmap: Optional[str]
  opacity: Optional[float]
}
class arcgis.raster._layer.RasterCatalogItem {
  _url: None
  _con: None
  _service: None
}
class arcgis.raster._layer.RasterCollection {
  _context: None
  _context: Optional[dict]
  _ras_coll_engine: None
  _ras_coll_engine_obj: None
  _ras_coll_engine_obj: None
  _ras_coll_engine_obj: None
  _ras_coll_engine_obj: None
  _ras_coll_engine_obj: None
}
class arcgis.raster._layer.RasterManager {
  _service: None
}
class arcgis.raster._layer._ArcpyRaster {
  _gis: None
  _is_multidimensional: None
  _raster: None
  _uri: None
  _path: None
  _raster: None
  _raster: None
  _raster: None
  _raster: None
  _uri: None
  _path: None
  _datastore_raster: None
  _do_not_hydrate: None
  _extent_set: None
  _extent: None
}
class arcgis.raster._layer._ArcpyRasterCollection {
  _mosaic_rule: None
  _gis: None
  _gis: None
  _where_clause: None
  _where_clause: None
  _spatial_filter: None
  _spatial_filter: None
  _attribute_dict: None
  _local: None
  _rasters: None
  _ras_coll_engine: None
  _context: None
  _context: None
  _raster_collection: None
  _raster_collection: None
  _raster_collection: None
  _raster_collection: None
  _df: None
}
class arcgis.raster._layer._ImageServerRaster {
  _gis: None
  _is_multidimensional: None
  _path: None
  _do_not_hydrate: None
  _created_from_collection: None
  _mdinfo: None
  _extent: None
  _extent_set: None
}
class arcgis.raster._layer._ImageServerRasterCollection {
  _mosaic_rule: None
  _gis: None
  _gis: None
  _where_clause: None
  _where_clause: None
  _spatial_filter: None
  _spatial_filter: None
  _rasters: None
  _attribute_dict: None
  _object_ids: None
  _raster_query: None
  _order_by_fields: None
  _do_not_hydrate: None
  _is_multidimensional: None
  _engine_obj: None
  _ras_coll_engine: None
  _df: None
  _context: None
  _context: None
  _df: None
  _start: None
  _lower_limit: None
  _upper_limit: None
  _max_rec_count: None
  _rep_df: None
  _order_by_fields: None
  _count: None
}
class arcgis.raster._layer._LocalRasterCollection {
  _mosaic_rule: None
  _gis: None
  _gis: None
  _where_clause: None
  _where_clause: None
  _spatial_filter: None
  _spatial_filter: None
  _rasters: None
  _object_ids: None
  _order_by_fields: None
  _is_multidimensional: None
  _engine_obj: None
  _ras_coll_engine: None
  _context: None
  _context: None
  _attribute_dict: None
  _df: None
}
class arcgis.raster._layer._RasterRenderingService {
  gis: None
  url: None
  token: None
  token: None
}
class arcgis.raster._util._ImageryUploaderAGOL {
  ClientAuthenticationError: None
  ServiceResponseError: None
  ServiceRequestError: None
  file_list: None
  container: None
  auto_renew: None
  task: None
  gis: None
  all_files: None
  mosaic_data_info: None
  url_list: None
  max_upload_concurrency: None
  max_upload_concurrency: None
  max_worker_threads: None
  max_worker_threads: None
  display_progress: None
  display_progress: None
  display_progress: None
}
arcgis.raster._layer.Raster <|-- arcgis.raster._layer._ArcpyRaster
arcgis.raster._layer.ImageryLayer <|-- arcgis.raster._layer._ArcpyRaster
arcgis.raster._layer.RasterCollection <|-- arcgis.raster._layer._ArcpyRasterCollection
arcgis.raster._layer.ImageryLayer <|-- arcgis.raster._layer._ArcpyRasterCollection
arcgis.raster._layer.ImageryLayer <|-- arcgis.raster._layer._ImageServerRaster
arcgis.raster._layer.Raster <|-- arcgis.raster._layer._ImageServerRaster
arcgis.raster._layer.ImageryLayer <|-- arcgis.raster._layer._ImageServerRasterCollection
arcgis.raster._layer.RasterCollection <|-- arcgis.raster._layer._ImageServerRasterCollection
arcgis.raster._layer.ImageryLayer <|-- arcgis.raster._layer._LocalRasterCollection
arcgis.raster._layer.RasterCollection <|-- arcgis.raster._layer._LocalRasterCollection
@enduml
